<?php

namespace AppBundle\Repository;

/**
 * ActuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActuRepository extends \Doctrine\ORM\EntityRepository
{

    public function getListInActu($user){
        return $this->createQueryBuilder("a")
            ->leftJoin("a.langue", "l")
            ->leftJoin("a.users", "u")
            ->addSelect("a", "l", "u")
            ->andWhere("a.users = :users")
            ->setParameter("users", $user)
            ->orderBy("a.createdAt", "DESC")
            ->getQuery()
            ->getResult();
    }
}
