<?php

namespace AppBundle\Repository;

/**
 * DiaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiaryRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $user
     * @return array
     */
    public function getListInDiary($user){
        return $this->createQueryBuilder("d")
            ->leftJoin("d.langue", "l")
            ->leftJoin("d.users", "u")
            ->addSelect("d", "l", "u")
            ->andWhere("d.users = :users")
            ->setParameter("users", $user)
            ->orderBy("d.createdAt", "DESC")
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $limit
     * @return array
     */
    public function getDiaryHome($limit){
        return $this->createQueryBuilder("d")
            ->leftJoin("d.langue", "l")
            ->leftJoin("d.users", "u")
            ->addSelect("d", "l", "u")
            ->orderBy("RAND()")
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

}
