<?php

namespace AppBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Query-builder Login
     * @return array
     */
    public function authorizedAccess($email, $password) {
        return $this->createQueryBuilder("u")
            ->addSelect("u")
            ->andWhere("u.email = :email")
            ->andWhere("u.password = :password")
            ->setParameter("email", $email)
            ->setParameter("password", $password)
            ->getQuery()
            ->execute();
    }

    /**
     * Return getPassword is users id
     * @param $id
     * @return mixed
     */
    public function isMyPassword($id) {
        return $this->createQueryBuilder('u')
            ->addSelect('u.password')
            ->andWhere('u.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->execute();
    }

    /**
     * Return the users table and the data table assiciate
     */
    public function findAllWithAssociateTable(){
        return $this->createQueryBuilder("u")
            ->leftJoin("u.ville", "v")
            ->addSelect("v")
            ->orderBy("u.createdAt", "DESC")
            ->getQuery()
            ->getResult();
    }

}
