<?php

namespace AppBundle\Repository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Return row ville in id
     * @param $ville
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getVille($ville){
        return $this->createQueryBuilder("v")
            ->addSelect("v")
            ->andWhere("v.libelle = :ville")
            ->setParameter("ville", $ville)
            ->getQuery()
            ->execute();
    }
}
