# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous:


    access_control:
        # require has_role Anonymously for Login, Register, ForgotStepOne and ForgotStepTwo
        #- { path: ^/, allow_if: "not has_role('ROLE_USER', 'ROLE_ADMIN')" }
        #- { path: ^/register, allow_if: "not has_role('ROLE_USER', 'ROLE_ADMIN')" }
        #- { path: ^/forgot, allow_if: "not has_role('ROLE_USER', 'ROLE_ADMIN')" }
        #- { path: ^/forgotStepFinal, allow_if: "not has_role('ROLE_USER', 'ROLE_ADMIN')" }
